spring:
  application:
    name: pm-gh-integration
  kafka:
    bootstrap-servers: localhost:29092
  data:
    mongodb:
      database: pm_gh
      username: example
      password: example
      authentication-database: admin
      port: 27017
      host: localhost
  security:
    jwt:
      secret: "0123456789ABCDEF0123456789ABCDEF"
      expiration-in-seconds: 3600